### ISSUE TITLE
Elasticsearch on Raspberry Pi 4

### ISSUE THREAD

**Issue by Fire-Frog** [tubearchivist/tubearchivist#240]
I'm trying to get tubearchivist on my Raspberry PI 4, but I've unsuccessful on it.
I changed some things around to use arm64 images, but i keep getting this log `tubearchivist    | waiting for elastic search to start`

I know the problem is Elasticsearch but i couldn't figure it out how to fix it.
Is there anything i can do to setup up my rpi correctly with docker-compose?

This is my docker-compose.yml modified trying to run everything:
```
version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: always
    image: bbilly1/tubearchivist:latest
    ports:
      - 8000:8000
    volumes:
      - media:/youtube
      - cache:/cache
    environment:
      - ES_URL=http://192.168.0.10:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_USERNAME=tubearchivist           # your initial TA credentials
      - TA_PASSWORD=verysecret              # your initial TA credentials
      - ELASTIC_PASSWORD=verysecret         # set password for Elasticsearch
      - TZ=America/New_York                 # set your time zone
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: bbilly1/rejson  #changed for rpi
    container_name: archivist-redis
    restart: always
    expose:
      - "6379"
    volumes:
      - redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2 #changed for rpi
    container_name: archivist-es
    restart: always
    environment:
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=verysecret"       # matching Elasticsearch password
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"

volumes:
  media:
  cache:
  redis:
  es:
```
