### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by ironicbadger** [tubearchivist/tubearchivist#245]
```
2022-05-06T19:11:49.465807744Z [2022-05-06 15:11:49,465: WARNING/ForkPoolWorker-4] downloading 1 thumbnails
2022-05-06T19:12:05.898812230Z [2022-05-06 15:12:05,898: WARNING/ForkPoolWorker-4] WARNING: [youtube] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)>. Retrying ...
2022-05-06T19:12:16.510045876Z [2022-05-06 15:12:16,509: WARNING/ForkPoolWorker-4] WARNING: [youtube] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)>. Retrying ...
```

This looks like an issue specific to the underlying youtube-dl (or whatever) implementation TA is using. Can I specify the `--no-check-certificate` option temporarily or can anyone give me a clue why I'm seeing this errors?

As a consequence the channels I've added show 0 videos.

<img width="783" alt="image" src="https://user-images.githubusercontent.com/2773080/167203212-ac915356-6db6-47e0-b8cf-6ad69167299e.png">

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/2773080/167203260-c73ee3cd-0175-4f4c-8620-43bd2d685cc0.png">

**Comment by ironicbadger** [comment]
```yaml
  ta:
    image: bbilly1/tubearchivist:latest
    container_name: ta
    volumes:
      - /mnt/storage/youtube:/youtube
      - /mnt/nvme2tb/appdata/tubearchivist/cache:/cache
    labels:
      - traefik.enable=true
      - traefik.http.routers.tubearchivist.rule=Host(`tube.m.wd.ktz.me`)
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - ES_URL=http://ta-elastic:9200
      - REDIS_HOST=ta-redis
      - TA_USERNAME=123
      - TA_PASSWORD=123
      - ELASTIC_PASSWORD=123
      - HOST_UID=1000
      - HOST_GID=1000
    depends_on:
      - ta-elastic
      - ta-redis
    restart: unless-stopped
  ta-redis:
    image: redislabs/rejson:latest
    container_name: ta-redis
    volumes:
      - /mnt/nvme2tb/appdata/tubearchivist/redis:/data
    depends_on:
      - ta-elastic
    restart: unless-stopped
  ta-elastic:
    image: bbilly1/tubearchivist-es
    container_name: ta-elastic
    volumes:
      - /mnt/nvme2tb/appdata/tubearchivist/elastic:/usr/share/elasticsearch/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=123
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
```
