### ISSUE TITLE
Cannot download long videos

### ISSUE THREAD

**Issue by Ra5CZ** [tubearchivist/tubearchivist#246]
Hi,
I tried download videos +-3h long, but nothing happend. Any error in log, anything.

Can anyone try download [this](https://www.youtube.com/watch?v=G4VAxch6yEI) or [this](https://www.youtube.com/watch?v=dgIAMvKjb9U)?

With regards
Petr

**Comment by bbilly1** [comment]
Both of these videos downloaded fine for me. 

Try recreating the container with the environment variable `DJANGO_DEBOG=True` set to get some more debug output.

**Comment by Ra5CZ** [comment]
Don't see any error.
```
https://www.youtube.com/watch?v=dgIAMvKjb9U
processing: https://www.youtube.com/watch?v=dgIAMvKjb9U
ParseResult(scheme='https', netloc='www.youtube.com', path='/watch', params='', query='v=dgIAMvKjb9U', fragment='')
[{'url': 'dgIAMvKjb9U', 'type': 'video'}]
[2022-05-17 17:45:54,414: INFO/MainProcess] Task home.tasks.extrac_dl[f221507d-37ff-4e3c-b2e0-a9024b565ce2] received
[2022-05-17 17:45:54,760: INFO/ForkPoolWorker-1] Task home.tasks.extrac_dl[f221507d-37ff-4e3c-b2e0-a9024b565ce2] succeeded in 0.34307849197648466s: None
[pid: 46|app: 0|req: 37/37] 192.168.96.1 () {72 vars in 1478 bytes} [Tue May 17 17:45:54 2022] POST /downloads/ => generated 0 bytes in 2103 msecs (HTTP/1.1 301) 8 headers in 265 bytes (1 switches on core 0)
[pid: 46|app: 0|req: 38/38] 192.168.96.1 () {66 vars in 1320 bytes} [Tue May 17 17:45:56 2022] GET /downloads/ => generated 6223 bytes in 75 msecs (HTTP/1.1 200) 8 headers in 398 bytes (1 switches on core 0)
[pid: 46|app: 0|req: 39/39] 192.168.96.1 () {64 vars in 1220 bytes} [Tue May 17 17:45:56 2022] GET /static/css/style.css => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 204 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 40/40] 192.168.96.1 () {64 vars in 1198 bytes} [Tue May 17 17:45:56 2022] GET /static/script.js => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 204 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 41/41] 192.168.96.1 () {64 vars in 1217 bytes} [Tue May 17 17:45:56 2022] GET /static/css/dark.css => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 42/42] 192.168.96.1 () {64 vars in 1308 bytes} [Tue May 17 17:45:56 2022] GET /static/img/banner-tube-archivist-dark.png => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 204 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 43/43] 192.168.96.1 () {64 vars in 1201 bytes} [Tue May 17 17:45:56 2022] GET /static/progress.js => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 44/44] 192.168.96.1 () {64 vars in 1277 bytes} [Tue May 17 17:45:56 2022] GET /static/img/icon-search.svg => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 45/45] 192.168.96.1 () {64 vars in 1273 bytes} [Tue May 17 17:45:56 2022] GET /static/img/icon-gear.svg => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 46/46] 192.168.96.1 () {64 vars in 1274 bytes} [Tue May 17 17:45:56 2022] GET /static/img/icon-exit.svg => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 204 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 47/47] 192.168.96.1 () {60 vars in 1088 bytes} [Tue May 17 17:45:56 2022] GET /progress/ => generated 127 bytes in 15 msecs (HTTP/1.1 200) 7 headers in 221 bytes (1 switches on core 0)
[pid: 46|app: 0|req: 48/48] 192.168.96.1 () {66 vars in 1268 bytes} [Tue May 17 17:45:56 2022] GET /static/font/Sen-Regular.woff => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 204 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 49/49] 192.168.96.1 () {64 vars in 1277 bytes} [Tue May 17 17:45:56 2022] GET /static/img/icon-rescan.svg => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 50/50] 192.168.96.1 () {66 vars in 1262 bytes} [Tue May 17 17:45:56 2022] GET /static/font/Sen-Bold.woff => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 204 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 51/51] 192.168.96.1 () {64 vars in 1281 bytes} [Tue May 17 17:45:56 2022] GET /static/img/icon-download.svg => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 52/52] 192.168.96.1 () {64 vars in 1282 bytes} [Tue May 17 17:45:56 2022] GET /static/img/icon-gridview.svg => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 204 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 53/53] 192.168.96.1 () {64 vars in 1271 bytes} [Tue May 17 17:45:56 2022] GET /static/img/icon-add.svg => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 54/54] 192.168.96.1 () {64 vars in 1281 bytes} [Tue May 17 17:45:56 2022] GET /static/img/icon-listview.svg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 55/55] 192.168.96.1 () {62 vars in 1093 bytes} [Tue May 17 17:45:56 2022] GET /static/favicon/site.webmanifest => generated 0 bytes in 1 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 56/56] 192.168.96.1 () {60 vars in 1088 bytes} [Tue May 17 17:46:00 2022] GET /progress/ => generated 127 bytes in 12 msecs (HTTP/1.1 200) 7 headers in 221 bytes (1 switches on core 0)
[pid: 46|app: 0|req: 57/57] 192.168.96.1 () {60 vars in 1088 bytes} [Tue May 17 17:46:04 2022] GET /progress/ => generated 127 bytes in 12 msecs (HTTP/1.1 200) 7 headers in 221 bytes (1 switches on core 0)
[pid: 46|app: 0|req: 58/58] 192.168.96.1 () {60 vars in 1088 bytes} [Tue May 17 17:46:07 2022] GET /progress/ => generated 127 bytes in 12 msecs (HTTP/1.1 200) 7 headers in 221 bytes (1 switches on core 0)
[pid: 46|app: 0|req: 59/59] 192.168.96.1 () {60 vars in 1088 bytes} [Tue May 17 17:46:10 2022] GET /progress/ => generated 127 bytes in 12 msecs (HTTP/1.1 200) 7 headers in 221 bytes (1 switches on core 0)
[pid: 46|app: 0|req: 60/60] 192.168.96.1 () {60 vars in 1088 bytes} [Tue May 17 17:46:13 2022] GET /progress/ => generated 127 bytes in 12 msecs (HTTP/1.1 200) 7 headers in 221 bytes (1 switches on core 0)
[pid: 46|app: 0|req: 61/61] 192.168.96.1 () {60 vars in 1088 bytes} [Tue May 17 17:46:16 2022] GET /progress/ => generated 16 bytes in 12 msecs (HTTP/1.1 200) 7 headers in 220 bytes (1 switches on core 0)
[pid: 46|app: 0|req: 62/62] 192.168.96.1 () {64 vars in 1295 bytes} [Tue May 17 17:46:16 2022] GET /downloads/ => generated 6223 bytes in 72 msecs (HTTP/1.1 200) 8 headers in 398 bytes (1 switches on core 0)
[pid: 46|app: 0|req: 63/63] 192.168.96.1 () {64 vars in 1220 bytes} [Tue May 17 17:46:16 2022] GET /static/css/style.css => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 204 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 64/64] 192.168.96.1 () {64 vars in 1198 bytes} [Tue May 17 17:46:16 2022] GET /static/script.js => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 204 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 65/65] 192.168.96.1 () {64 vars in 1217 bytes} [Tue May 17 17:46:16 2022] GET /static/css/dark.css => generated 0 bytes in 1 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 66/66] 192.168.96.1 () {64 vars in 1308 bytes} [Tue May 17 17:46:16 2022] GET /static/img/banner-tube-archivist-dark.png => generated 0 bytes in 1 msecs (HTTP/1.1 304) 6 headers in 204 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 67/67] 192.168.96.1 () {64 vars in 1201 bytes} [Tue May 17 17:46:16 2022] GET /static/progress.js => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 68/68] 192.168.96.1 () {64 vars in 1277 bytes} [Tue May 17 17:46:16 2022] GET /static/img/icon-search.svg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 69/69] 192.168.96.1 () {64 vars in 1271 bytes} [Tue May 17 17:46:16 2022] GET /static/img/icon-add.svg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 70/70] 192.168.96.1 () {64 vars in 1281 bytes} [Tue May 17 17:46:16 2022] GET /static/img/icon-download.svg => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 71/71] 192.168.96.1 () {64 vars in 1277 bytes} [Tue May 17 17:46:16 2022] GET /static/img/icon-rescan.svg => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 72/72] 192.168.96.1 () {64 vars in 1274 bytes} [Tue May 17 17:46:16 2022] GET /static/img/icon-exit.svg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 6 headers in 204 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 73/73] 192.168.96.1 () {64 vars in 1281 bytes} [Tue May 17 17:46:16 2022] GET /static/img/icon-listview.svg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 74/74] 192.168.96.1 () {64 vars in 1273 bytes} [Tue May 17 17:46:16 2022] GET /static/img/icon-gear.svg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 75/75] 192.168.96.1 () {64 vars in 1282 bytes} [Tue May 17 17:46:16 2022] GET /static/img/icon-gridview.svg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 6 headers in 204 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 76/76] 192.168.96.1 () {66 vars in 1268 bytes} [Tue May 17 17:46:16 2022] GET /static/font/Sen-Regular.woff => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 204 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 77/77] 192.168.96.1 () {66 vars in 1262 bytes} [Tue May 17 17:46:16 2022] GET /static/font/Sen-Bold.woff => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 204 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 78/78] 192.168.96.1 () {60 vars in 1088 bytes} [Tue May 17 17:46:16 2022] GET /progress/ => generated 16 bytes in 13 msecs (HTTP/1.1 200) 7 headers in 220 bytes (1 switches on core 0)
[pid: 46|app: 0|req: 79/79] 192.168.96.1 () {64 vars in 1278 bytes} [Tue May 17 17:46:16 2022] GET /static/favicon/favicon.ico => generated 0 bytes in 2 msecs (HTTP/1.1 304) 6 headers in 204 bytes (0 switches on core 0)
[pid: 46|app: 0|req: 80/80] 192.168.96.1 () {62 vars in 1093 bytes} [Tue May 17 17:46:16 2022] GET /static/favicon/site.webmanifest => generated 0 bytes in 4 msecs (HTTP/1.1 304) 6 headers in 203 bytes (0 switches on core 0)
```
This is last and only status
![image](https://user-images.githubusercontent.com/66022207/168854562-d545cdca-efe8-406b-9d09-cb50333a8eae.png)

**Comment by bbilly1** [comment]
Hard to say from afar what's going on. Can't reproduce that. What hardware are you running this on?

**Comment by Ra5CZ** [comment]
I'm using synology NAS with docker 20.10.3-1306

This is my docker-compose
```
version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: always
    image: bbilly1/tubearchivist:latest
    ports:
      - 63162:8000
    volumes:
      - /volume1/docker/tubearchivist/media:/youtube
      - /volume1/docker/tubearchivist/cache:/cache
    environment:
      - TZ=Europe/Prague
      - TA_USERNAME=xxxxx
      - TA_PASSWORD=xxxxxxxxxx
      - ELASTIC_PASSWORD=verysecret
      - ES_URL=http://archivist-es:9200
      - REDIS_HOST=archivist-redis
      - HOST_UID=1000
      - HOST_GID=1000      
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redislabs/rejson:latest
    container_name: archivist-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /volume1/docker/tubearchivist/redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: archivist-es
    restart: always
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /volume1/docker/tubearchivist/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
```
