### ISSUE TITLE
Tube Archivist and caddy-docker-proxy

### ISSUE THREAD

**Issue by OnigamiSama** [tubearchivist/tubearchivist#305]
Hello all.

I switched from "normal" caddy to [caddy-docker-proxy](https://github.com/lucaslorentz/caddy-docker-proxy)

The docker-compose.yml looks like this

```
version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8084:8000
    volumes:
      - /home/onigami/docker/containers/tubearchivist/cache:/cache
      - /zdata/mediaserver/library/vod:/youtube
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=sub.domain.com          # set your host name
      - TA_USERNAME=onigami                 # your initial TA credentials
      - TA_PASSWORD=passwd        # your initial TA credentials
      - ELASTIC_PASSWORD=passwd   # set password for Elasticsearch
      - TZ=Europe/Paris                     # set your time zone
    depends_on:
      - archivist-es
      - archivist-redis
    networks:
      - caddy
    labels:
      caddy: sub.domain.com
      caddy.reverse_proxy: "{{upstreams 8000}}"

  archivist-redis:
    image: redislabs/rejson                 # for arm64 use bbilly1/rejson
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - /home/onigami/docker/containers/tubearchivist/redis:/data
    depends_on:
      - archivist-es

  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.3.2
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=passwd # matching Elasticsearch password
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/onigami/docker/containers/tubearchivist/es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"

networks:
  caddy:
    external: true
```

But with this configuration tubearchivist is not able to communicate with archivist-es, the error in logs

```
tubearchivist      | waiting for elastic search to start
tubearchivist      | failed to connect to elastic search, exiting...
```

The containers should have acces to two networks, the caddy one and the tubearchivist_default one right ?

If I remove the caddy lines in the docker-compose everything works fine but I lose the reverse proxy.

So I guess the issue is that http://archivist-es:9200 is unreachable.

Should I put the other containers on the caddy network ? It seems strange to me to do it this way.

**Comment by OnigamiSama** [comment]
Putin the archivist-es and archivist-redis containers on the caddy network indeed solved the issue.

But is it consiodered "best pratice" ?

```
version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8084:8000
    volumes:
      - /home/onigami/docker/containers/tubearchivist/cache:/cache
      - /zdata/mediaserver/library/vod:/youtube
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=sub.domain.com          # set your host name
      - TA_USERNAME=onigami                 # your initial TA credentials
      - TA_PASSWORD=passwd        # your initial TA credentials
      - ELASTIC_PASSWORD=passwd   # set password for Elasticsearch
      - TZ=Europe/Paris                     # set your time zone
    depends_on:
      - archivist-es
      - archivist-redis
    networks:
      - caddy
    labels:
      caddy: sub.domain.com
      caddy.reverse_proxy: "{{upstreams 8000}}"

  archivist-redis:
    image: redislabs/rejson                 # for arm64 use bbilly1/rejson
    container_name: archivist-redis
    restart: unless-stopped
    networks:
      - caddy
    expose:
      - "6379"
    volumes:
      - /home/onigami/docker/containers/tubearchivist/redis:/data
    depends_on:
      - archivist-es

  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.3.2
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=passwd # matching Elasticsearch password
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/onigami/docker/containers/tubearchivist/es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    networks:
      - caddy
    expose:
      - "9200"

networks:
  caddy:
    external: true
```
