### ISSUE TITLE
[Bug][Hotfix pubished]: new update 0.2.1 lead to web error 500

### ISSUE THREAD

**Issue by lue30499** [tubearchivist/tubearchivist#310]
- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).

### Operating System

linux

## Description
After changing the version number to 0.2.1 in the docker-compose and up-ing the new version leads to the web-ui being inaccessable and having a "Server Error (500)"
(please note that this worked before the update and works if I change it back to 0.2.0)

here is my docker compose :
```
version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist:v0.2.1
    ports:
      - "6004:8000"
    volumes:
      - /mnt/nasmounts/video/YouTube/tubearchivist/data:/youtube
      - /mnt/nasmounts/video/YouTube/tubearchivist/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200
      - REDIS_HOST=archivist-redis
      - HOST_UID=1102
      - HOST_GID=1102
      - TA_HOST=srv-l-01.domain.internal
      - TA_USERNAME=admin
      - TA_PASSWORD=<password1>
      - ELASTIC_PASSWORD=<password2>
      - TZ=Australia/Sydney
    depends_on:
      - archivist-es
      - archivist-redis
    deploy:
      resources:
        limits:
          memory: 512M

  archivist-redis:
    image: redislabs/rejson:2.0.11
    container_name: archivist-redis
    restart: unless-stopped
    environment:
      - TZ=Australia/Sydney
    expose:
      - "6379"
    volumes:
      - /docker/mounts/tubearchivist/redis:/data
    depends_on:
      - archivist-es
    deploy:
      resources:
        limits:
          memory: 32M

  archivist-es:
    image: bbilly1/tubearchivist-es:8.3.3
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=<password2>"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Australia/Sydney
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /docker/mounts/tubearchivist/es:/usr/share/elasticsearch/data
    expose:
      - "9200"
    deploy:
      resources:
        limits:
          memory: 1024M
```

### Relevant log output

```shell
## Logs from docker

tubearchivist      | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
tubearchivist      | --- ***** ----- 
tubearchivist      |  -------------- [queues]
tubearchivist      |                 .> celery           exchange=celery(direct) key=celery
tubearchivist      |                 
tubearchivist      | 
tubearchivist      | [tasks]
tubearchivist      |   . check_reindex
tubearchivist      |   . download_pending
tubearchivist      |   . home.tasks.download_single
tubearchivist      |   . home.tasks.extrac_dl
tubearchivist      |   . home.tasks.index_channel_playlists
tubearchivist      |   . home.tasks.re_sync_thumbs
tubearchivist      |   . home.tasks.rescan_filesystem
tubearchivist      |   . home.tasks.run_manual_import
tubearchivist      |   . home.tasks.run_restore_backup
tubearchivist      |   . home.tasks.subscribe_to
tubearchivist      |   . run_backup
tubearchivist      |   . thumbnail_check
tubearchivist      |   . update_subscribed
tubearchivist      | 
tubearchivist      | [2022-08-20 12:16:54,536: INFO/MainProcess] Connected to redis://archivist-redis:6379//
tubearchivist      | [2022-08-20 12:16:54,541: INFO/MainProcess] mingle: searching for neighbors
tubearchivist      | [2022-08-20 12:16:55,550: INFO/MainProcess] mingle: all alone
tubearchivist      | [2022-08-20 12:16:55,562: INFO/MainProcess] celery@0257d123572d ready.
tubearchivist      | [pid: 26|app: 0|req: 1/1] 10.100.10.86 () {48 vars in 962 bytes} [Sat Aug 20 12:18:14 2022] GET / => generated 145 bytes in 499 msecs (HTTP/1.1 500) 7 headers in 248 bytes (1 switches on core 0)
tubearchivist      | [pid: 26|app: 0|req: 2/2] 10.100.10.86 () {48 vars in 962 bytes} [Sat Aug 20 12:18:16 2022] GET / => generated 145 bytes in 332 msecs (HTTP/1.1 500) 7 headers in 248 bytes (1 switches on core 0)
tubearchivist      | [pid: 26|app: 0|req: 3/3] 10.100.10.86 () {48 vars in 962 bytes} [Sat Aug 20 12:18:16 2022] GET / => generated 145 bytes in 330 msecs (HTTP/1.1 500) 7 headers in 248 bytes (1 switches on core 0)
tubearchivist      | [pid: 26|app: 0|req: 4/4] 10.100.10.86 () {48 vars in 962 bytes} [Sat Aug 20 12:18:21 2022] GET / => generated 145 bytes in 332 msecs (HTTP/1.1 500) 7 headers in 248 bytes (1 switches on core 0)

```
```


### Anything else?

![Screenshot from 2022-08-20 12-25-53](https://user-images.githubusercontent.com/63104612/185725654-9a1a8e5e-550b-4e4d-bb4e-e5a9605a6913.png)
