### ISSUE TITLE
[Bug]: latest rejson image breaks archivist-redis

### ISSUE THREAD

**Issue by hugalafutro** [tubearchivist/tubearchivist#354]
### Latest and Greatest

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).

### Operating System

Linux

## Describe the bug
I just got diun notification the image updated, after pulling and recreating the stack tube-archivist doesn't start do more due to failing redis container

## Steps To Reproduce
docker compose up -d
observe the non-starting redis container.

## Expected behavior
stack should start as normal

### Relevant log output

```shell
archivist-redis  | 1:C 28 Oct 2022 14:01:37.190 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
archivist-redis  | 1:C 28 Oct 2022 14:01:37.190 # Redis version=6.2.7, bits=64, commit=00000000, modified=0, pid=1, just started
archivist-redis  | 1:C 28 Oct 2022 14:01:37.190 # Configuration loaded
archivist-redis  | 1:M 28 Oct 2022 14:01:37.191 * monotonic clock: POSIX clock_gettime
archivist-redis  | 1:M 28 Oct 2022 14:01:37.192 # A key '__redis__compare_helper' was added to Lua globals which is not on the globals allow list nor listed on the deny list.
archivist-redis  | 1:M 28 Oct 2022 14:01:37.192 * Running mode=standalone, port=6379.
archivist-redis  | 1:M 28 Oct 2022 14:01:37.192 # Server initialized
archivist-redis  | 1:M 28 Oct 2022 14:01:37.193 * <ReJSON> version: 20400 git sha: e383c08 branch: HEAD
archivist-redis  | 1:M 28 Oct 2022 14:01:37.193 * <ReJSON> Exported RedisJSON_V1 API
archivist-redis  | 1:M 28 Oct 2022 14:01:37.193 * <ReJSON> Exported RedisJSON_V2 API
archivist-redis  | 1:M 28 Oct 2022 14:01:37.193 * <ReJSON> Enabled diskless replication
archivist-redis  | 1:M 28 Oct 2022 14:01:37.193 * <ReJSON> Created new data type 'ReJSON-RL'
archivist-redis  | 1:M 28 Oct 2022 14:01:37.193 * Module 'ReJSON' loaded from /usr/lib/redis/modules/rejson.so
archivist-redis  | 1:M 28 Oct 2022 14:01:37.194 * Loading RDB produced by version 6.2.7
archivist-redis  | 1:M 28 Oct 2022 14:01:37.194 * RDB age 12 seconds
archivist-redis  | 1:M 28 Oct 2022 14:01:37.194 * RDB memory usage when created 1.04 Mb
archivist-redis  | 1:M 28 Oct 2022 14:01:37.194 # The RDB file contains AUX module data I can't load: no matching module 'scdtype00'
```

### Anything else?

docker-compose.yml for reference:

```
version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: always
    image: bbilly1/tubearchivist:latest
    ports:
      - 8543:8000
    volumes:
      - /shares/nfs/private/_tube-archivist:/youtube
      - /shares/nfs/private/_tube-archivist/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200
      - TA_HOST=${TA_HOSTLIST}
      - REDIS_HOST=archivist-redis
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_USERNAME=${TA_NAME}
      - TA_PASSWORD=${TA_PASS}
      - ELASTIC_PASSWORD=${ES_PASS}
      - TZ=${TIMEZONE}
    depends_on:
      - archivist-es
      - archivist-redis

  archivist-redis:
    image: redislabs/rejson:latest
    container_name: archivist-redis
    restart: always
    expose:
      - "6379"
    volumes:
      - ./redis:/data
    depends_on:
      - archivist-es

  archivist-es:
    image: bbilly1/tubearchivist-es
    container_name: archivist-es
    restart: always
    environment:
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=${ES_PASS}"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es:/usr/share/elasticsearch/data
    expose:
      - "9200"

```
