### ISSUE TITLE
[Installation]: VM storage growing exponentially

### ISSUE THREAD

**Issue by voarsh2** [tubearchivist/tubearchivist#391]
### Installation instructions

- [X] I have read and understand the [installation instructions](https://github.com/tubearchivist/tubearchivist#installing-and-updating).
- [X] My issue is not described in the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux

### Your installation or setup question

My docker-compose file:

```
version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8000:8000
    network_mode: "host"
    volumes:
      - /storage/tas-uploads/tubearchivist:/youtube
      - ./cache:/cache
    environment:
      - ES_URL=http://192.168.110.163:9200     # needs protocol e.g. http and port
      - REDIS_HOST=192.168.110.163          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=192.168.110.163         # set your host name
      - TA_USERNAME=X           # your initial TA credentials
      - TA_PASSWORD=X              # your initial TA credentials
      - ELASTIC_PASSWORD=X         # set password for Elasticsearch
      - TZ=America/New_York                 # set your time zone
    depends_on:
      - archivist-es
      - archivist-redis
    volumes:
      - /etc/resolv.conf:/etc/resolv.conf
  archivist-redis:
    image: redislabs/rejson                 # for arm64 use bbilly1/rejson
    container_name: archivist-redis
    restart: unless-stopped
    network_mode: "host"
    expose:
      - "6379"
    volumes:
      - ./redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.5.1
    container_name: archivist-es
    restart: unless-stopped
    network_mode: "host"
    environment:
      - "ELASTIC_PASSWORD=verysecret"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"
```

My VM/LXC container's storage keeps getting bigger when downloading files, but doesn't shrink, a DB/elastic search DB, I wouldn't have thought would grow to 100GB's for 340 videos?
Should I mount /cache outside of this VM/LXC - the media "/youtube" is an external mountpoint for video storage, that wouldn't count against the VM/LXC container size.....

### Relevant log output

```shell
NA
```
