### ISSUE TITLE
[Installation]: Bad Request (400), TA_HOST with reverse proxy

### ISSUE THREAD

**Issue by purashy** [tubearchivist/tubearchivist#400]
### Installation instructions

- [X] I have read and understand the [installation instructions](https://github.com/tubearchivist/tubearchivist#installing-and-updating).
- [ ] My issue is not described in the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux (Debian 10)

### Your installation or setup question

Trying to install Tubearchivist via docker (`VM created in proxmox (not lxc, actual VM)`).
Saw the below on the documentation about my error (`bad request (400)`).

```
Set the environment variable TA_HOST to match with the system running Tube Archivist.
This can be a domain like example.com, a subdomain like ta.example.com or an IP address like 192.168.1.20,
add without the protocol and without the port. You can add multiple hostnames separated with a space.
Any wrong configurations here will result in a Bad Request (400) response.
```

My docker-compose.yaml does include `TA_HOST=192.168.x.x`

However, i still get `Bad Request (400)`.

Below is my `docker-compose` file.

```
version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8000:8000
    volumes:
      - /path/to/youtube:/youtube
      - /path/to/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200
      - REDIS_HOST=archivist-redis
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=192.168.2.1xx
      - TA_USERNAME=username
      - TA_PASSWORD=password
      - ELASTIC_PASSWORD=password
      - TZ=Europe/Amsterdam
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redislabs/rejson
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - /path/to/redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=password"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /path/to/es:/usr/share/elasticsearch/data
    expose:
      - "9200"
```

Thank you for any help <3

### Relevant log output

```shell
[2023-01-05 01:33:54,403: INFO/MainProcess] celery@c88902ecf4bd ready.
[2023-01-05 01:33:54,390: INFO/MainProcess] mingle: all alone
[2023-01-05 01:33:53,380: INFO/MainProcess] mingle: searching for neighbors
[2023-01-05 01:33:53,373: INFO/MainProcess] Connected to redis://archivist-redis:6379//
  . thumbnail_check
  . run_backup
  . home.tasks.subscribe_to
  . home.tasks.run_restore_backup
  . home.tasks.run_manual_import
  . home.tasks.rescan_filesystem
  . home.tasks.re_sync_thumbs
  . home.tasks.extrac_dl
  . home.tasks.download_single
  . home.tasks.index_channel_playlists
  . download_pending
  . check_reindex
[tasks]
                
  . update_subscribed
                .> celery           exchange=celery(direct) key=celery
 -------------- [queues]
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
- *** --- * --- .> concurrency: 2 (prefork)
- ** ---------- .> results:     disabled://
- ** ---------- .> transport:   redis://archivist-redis:6379//
- ** ---------- .> app:         tasks:0x7f6513be37c0
- ** ---------- [config]
- *** --- * --- 
-- ******* ---- Linux-5.10.0-20-amd64-x86_64-with-glibc2.31 2023-01-05 01:33:53
--- ***** ----- 
 -------------- celery@c88902ecf4bd v5.2.7 (dawn-chorus)
```

**Edit:**
Seems to be working now. However, there is some sort of reverse proxy issue.
Navigating to `IP:Port` works. However, navigating to `sub.domain.com` gives `Bad Request (400)`.
