### ISSUE TITLE
[Installation]: Elastic Search failing to connect

### ISSUE THREAD

**Issue by sirjacob2u** [tubearchivist/tubearchivist#417]
### Installation instructions

- [X] I have read and understand the [installation instructions](https://github.com/tubearchivist/tubearchivist#installing-and-updating).
- [x] My issue is not described in the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Fedora Server

### Your installation or setup question

Elastic search fails to start after about a minute. I think I'm missing something stupid. Here is my docker-compose file as well.

```
version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8010:8000
    volumes:
      - /mnt/sda/tube:/youtube
      - ./volumes/tubearchivist/cache:/cache
    environment:
      - ES_URL=http://192.168.1.52:9200     # needs protocol e.g. http and port
      - REDIS_HOST=192.168.1.52          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=HOSTNAME         # set your host name
      - TA_USERNAME=USERNAME           # your initial TA credentials
      - TA_PASSWORD=PASSWORD              # your initial TA credentials
      - ELASTIC_PASSWORD=PASSWORD              # set password for Elasticsearch
      - TZ=America/New_York                 # set your time zone
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redislabs/rejson                 # for arm64 use bbilly1/rejson
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - ./volumes/tubearchivist/redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.6.0
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=PASSWORD"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./volumes/tubearchivist/es:/usr/share/elasticsearch/data    # check for permission error when using bind mount,>    
    expose:
      - "9200"

```

### Relevant log output

```shell
tubearchivist      | waiting for elastic search to start
tubearchivist      | waiting for elastic search to start
tubearchivist      | waiting for elastic search to start
tubearchivist      | waiting for elastic search to start
tubearchivist      | waiting for elastic search to start
tubearchivist      | failed to connect to elastic search, exiting...
tubearchivist      | *   Trying 192.168.1.52:9200...
tubearchivist      |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
tubearchivist      |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* connect to 192.168.1.52 port 9200 failed: Connection refused
tubearchivist      | * Failed to connect to 192.168.1.52 port 9200: Connection refused
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
tubearchivist      | * Closing connection 0
tubearchivist      | curl: (7) Failed to connect to 192.168.1.52 port 9200: Connection refused
tubearchivist exited with code 1
tubearchivist      | waiting for elastic search to start
tubearchivist      | waiting for elastic search to start
tubearchivist      | waiting for elastic search to start
tubearchivist      | waiting for elastic search to start
tubearchivist      | waiting for elastic search to start
```
