### ISSUE TITLE
[Bug]: Upgrade not successful, no such snapshot lifecycle policy [ta_daily]

### ISSUE THREAD

**Issue by inoricat** [tubearchivist/tubearchivist#443]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

(docker) Linux raspberrypi 5.10.63-v8+ aarch64

## Describe the bug

When trying to update from a previous version, I missed to place some new ENV variables, and it errored out telling me to place them. 
After solving it, an error appears on tubearchivist logs saying that it doesnt recognize the snapshot lifecycle policy.
`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"no such snapshot lifecycle policy [ta_daily]"}],"type":"illegal_argument_exception","reason":"no such snapshot lifecycle policy [ta_daily]"},"status":400}`

I guess its a migration problem on elasticsearch, is there a way to solve it without restarting from 0 and rebuilding from the videos?

## Steps To Reproduce

Update from an old version (I don't exactly remember, but the reccomended ES version was 7.17.4)

## Expected behavior

Update works without issues after inputting the correct ENV vars.

### Relevant log output

```shell
.:0MMMMMMMMMMMMMMMMMMMX:     .cNMMMWx.   .;clc:,
     .;lOXK0000KNMMMMX00000KO;     ;KMMMMMNl.   .;ccl:,.,
     .;:c:'.....kMMMNo........    'OMMMWMMMK:    '::;;'.,
   .......     .xMMMNl           .dWMMXdOMMMO'   ........,
   .:cc:;.     .xMMMNc          .lNMMNo.:XMMWx.    .:cl:.,
   .:llc,.     .:xxxd,          ;KMMMk. .oWMMNl.   .:llc',
   .cll:.     .;:;;:::,.       'OMMMK:';''kWMMK:   .;llc,,
   .cll:.     .,;;;;;;,.     .,xWMMNl.:l:.;KMMMO'  .;llc',
   .:llc.      .cOOOk;      .lKNMMWx..:l:..lNMMWx. .:llc',
   .;lcc,.     .xMMMNc      :KMMMM0, .:lc. .xWMMNl.'ccl:.,
    .cllc.     .xMMMNc     'OMMMMXc...:lc...,0MMMKl:lcc,.,
    .,ccl:.    .xMMMNc    .xWMMMWo.,;;:lc;;;.cXMMMXdcc;.,
     .,clc:.   .xMMMNc   .lNMMMWk. .':clc:,. .dWMMW0o;.,
      .,clcc,. .ckkkx;   .okkkOx,    .';,.    'kKKK0l.,
       .':lcc:'.....      .  ..            ..,;cllc,.,
         .,cclc,....                     ....;clc;..,
          ..,:,..,c:'..              ...';:,..,:,.,
            ....:lcccc:;,'''.....'',;;:clllc,....,
               .'',;:cllllllccccclllllcc:,'..,
                   ...'',,;;;;;;;;;,''...,
                            .....,
,
,
#######################,
#  Environment Setup  #,
#######################,
,
[1] checking expected env vars,
    ✓ all expected env vars are set,
[2] set default ES user,
    ✓ ES user is set to elastic,
[3] check TA_PORT overwrite,
    ✓ TA_PORT already set to 9000,
[4] check TA_UWSGI_PORT overwrite,
    TA_UWSGI_PORT is not set,
[5] check ENABLE_CAST overwrite,
    ENABLE_CAST is not set,
[6] create superuser,
    superuser already created,
,
,
#######################,
#  Connection check   #,
#######################,
,
[1] connect to Redis,
    ✓ Redis connection verified,
[2] set Redis config,
    ✓ Redis config set,
[3] connect to Elastic Search,
    ... waiting for ES [0/24],
    ✓ ES connection established,
[4] Elastic Search version check,
    ✓ ES version check passed,
[5] check ES path.repo env var,
    ✓ path.repo env var is set,
,
,
#######################,
#  Application Start  #,
#######################,
,
[1] set new config.json values,
    no new config values,
[2] create expected cache folders,
    ✓ expected folders created,
[3] clear leftover locks in redis,
    no locks found,
[4] clear leftover files from dl cache,
clear download cache,
    no files found,
[5] check for first run after update,
    no new update found,
[MIGRATION] validate index mappings,
detected mapping change: channel_last_refresh, {'type': 'date'},
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"no such snapshot lifecycle policy [ta_daily]"}],"type":"illegal_argument_exception","reason":"no such snapshot lifecycle policy [ta_daily]"},"status":400},
Traceback (most recent call last):,
  File "/app/manage.py", line 23, in <module>,
    main(),
  File "/app/manage.py", line 19, in main,
    execute_from_command_line(sys.argv),
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line,
    utility.execute(),
  File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute,
    self.fetch_command(subcommand).run_from_argv(self.argv),
  File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv,
    self.execute(*args, **cmd_options),
  File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute,
    output = self.handle(*args, **options),
  File "/app/config/management/commands/ta_startup.py", line 39, in handle,
    self._mig_index_setup(),
  File "/app/config/management/commands/ta_startup.py", line 124, in _mig_index_setup,
    ElasitIndexWrap().setup(),
  File "/app/home/src/es/index_setup.py", line 160, in setup,
    self._check_backup(),
  File "/app/home/src/es/index_setup.py", line 205, in _check_backup,
    ElasticSnapshot().take_snapshot_now(wait=True),
  File "/app/home/src/es/snapshot.py", line 154, in take_snapshot_now,
    self._wait_for_snapshot(response["snapshot_name"]),
KeyError: 'snapshot_name'
```

### Anything else?

docker-compose.yml:
```
version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    image: bbilly1/tubearchivist:latest
    ports:
      - 9000:8000
    volumes:
      - /mnt/nave/tubearchivist:/youtube   # bind to external drive 
      - cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=192.168.4.9
      - TA_PORT=9000
      - TA_USERNAME=tubearchivist           # your initial TA credentials
      - TA_PASSWORD=*redacted* # your initial TA credentials
      - ELASTIC_PASSWORD=*redacted* # set password for Elasticsearch
      - TZ=Europe/Madrid                 # set your time zone
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: bbilly1/rejson                 # for arm64 use bbilly1/rejson
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: elasticsearch:8.6.0         # only for amd64, or use official es 7.17.4
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=*redacted*"       # matching Elasticsearch password
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "path.repo=/usr/share/elasticsearch/data/snapshot" 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"

volumes:
  media:
  cache:
  redis:
  es:
  
```
