### ISSUE TITLE
[Installation]: Everything seems ok but TubeArchivist is not reachable

### ISSUE THREAD

**Issue by CapitanCatarro** [tubearchivist/tubearchivist#473]
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

Linux

### Your installation or setup question

Hello there,
so I am trying to install TubeArchivist on docker, everything seems ok as you can see from the log section, but when I try to reach the web GUI it does not work...
I really can't understand what is the problem as on the same docker I have Portainer and PiHole and both of them are working correctly... 

### Relevant log output

```shell
tubearchivist      | LocalTime -> 2023-05-04 04:43:53
tubearchivist      | Configuration ->
tubearchivist      |     . broker -> redis://archivist-redis:6379//
tubearchivist      |     . loader -> celery.loaders.app.AppLoader
tubearchivist      |     . scheduler -> celery.beat.PersistentScheduler
tubearchivist      |     . db -> /celerybeat-schedule
tubearchivist      |     . logfile -> [stderr]@%INFO
tubearchivist      |     . maxinterval -> 5.00 minutes (300s)
tubearchivist      | [2023-05-04 04:43:53,385: INFO/MainProcess] beat: Starting...
tubearchivist      |  
tubearchivist      |  -------------- celery@069cddb8c940 v5.2.7 (dawn-chorus)
tubearchivist      | --- ***** ----- 
tubearchivist      | -- ******* ---- Linux-5.15.104-1-pve-x86_64-with-glibc2.31 2023-05-04 04:43:53
tubearchivist      | - *** --- * --- 
tubearchivist      | - ** ---------- [config]
tubearchivist      | - ** ---------- .> app:         tasks:0x7f5daf869e10
tubearchivist      | - ** ---------- .> transport:   redis://archivist-redis:6379//
tubearchivist      | - ** ---------- .> results:     redis://archivist-redis:6379/
tubearchivist      | - *** --- * --- .> concurrency: 4 (prefork)
tubearchivist      | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
tubearchivist      | --- ***** ----- 
tubearchivist      |  -------------- [queues]
tubearchivist      |                 .> celery           exchange=celery(direct) key=celery
tubearchivist      |                 
tubearchivist      | 
tubearchivist      | [tasks]
tubearchivist      |   . check_reindex
tubearchivist      |   . download_pending
tubearchivist      |   . extract_download
tubearchivist      |   . index_playlists
tubearchivist      |   . manual_import
tubearchivist      |   . rescan_filesystem
tubearchivist      |   . restore_backup
tubearchivist      |   . resync_thumbs
tubearchivist      |   . run_backup
tubearchivist      |   . subscribe_to
tubearchivist      |   . thumbnail_check
tubearchivist      |   . update_subscribed
tubearchivist      |   . version_check
tubearchivist      | 
tubearchivist      | [2023-05-04 04:43:54,042: INFO/MainProcess] Connected to redis://archivist-redis:6379//
tubearchivist      | [2023-05-04 04:43:54,048: INFO/MainProcess] mingle: searching for neighbors
tubearchivist      | [2023-05-04 04:43:55,062: INFO/MainProcess] mingle: all alone
tubearchivist      | [2023-05-04 04:43:55,083: INFO/MainProcess] celery@069cddb8c940 ready.
```

**Comment by lamusmaser** [comment]
How are you trying to access? What is your `TA_HOST` set to and does it include this method of access? You can find the details of it [here](https://docs.tubearchivist.com/installation/docker-compose/#configuring-tubearchivist).

**Comment by CapitanCatarro** [comment]
Hello again,
thanks for your answer.
This is the code I've used in my last try with Portainer, I've also tried `TA_HOST: http://192.168.2.199` without success, when I try to connect to http://192.168.2.199:7900 it says ERR_CONNECTION_REFUSED

```
version: '3.3'
services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 7900:7900
    volumes:
      - media:/youtube
      - cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=192.168.2.199         # set your host name
      - TA_USERNAME=tubearchivist           # your initial TA credentials
      - TA_PASSWORD=verysecret              # your initial TA credentials
      - ELASTIC_PASSWORD=verysecret         # set password for Elasticsearch
      - TZ=America/New_York                 # set your time zone
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.7.0
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - ELASTIC_PASSWORD=verysecret      # matching Elasticsearch password
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/data/snapshot
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - 9200

volumes:
  media:
  cache:
  redis:
  es:
```
