### ISSUE TITLE
[Bug]: After installing via Docker, fails to start with "Redis connection failed"

### ISSUE THREAD

**Issue by r0bbie** [tubearchivist/tubearchivist#606]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Ubuntu

## Describe the bug
Tried to spin up via Docker following instructions at https://docs.tubearchivist.com/installation/docker-compose/. Seemed to install successfully, but wasn't accessible in browser. On checking logs via `docker compose logs -f` noticed Redis connection was failing.

## Steps To Reproduce
Pulled down latest via git, made some minor edits to docker-compose.yml though to my knowledge nothing that should have impacted Redis behaviour, followed instructions to run via `docker compose up --detach`. 

## Expected behavior
Expected it to launch successfuly.

### Relevant log output

```shell
tubearchivist    | ... Redis connection failed, retry [0/10]
tubearchivist    | ... Redis connection failed, retry [1/10]
archivist-redis  | 8:C 19 Nov 2023 02:41:05.673 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
archivist-redis  | 8:C 19 Nov 2023 02:41:05.673 # Redis version=6.2.13, bits=64, commit=00000000, modified=0, pid=8, just started
archivist-redis  | 8:C 19 Nov 2023 02:41:05.673 # Configuration loaded
archivist-redis  | 8:M 19 Nov 2023 02:41:05.674 * monotonic clock: POSIX clock_gettime
archivist-redis  | 8:M 19 Nov 2023 02:41:05.674 * Running mode=standalone, port=6379.
archivist-redis  | 8:M 19 Nov 2023 02:41:05.674 # Server initialized
archivist-redis  | 8:M 19 Nov 2023 02:41:05.675 * <search> Redis version found by RedisSearch : 6.2.13 - oss
archivist-redis  | 8:M 19 Nov 2023 02:41:05.675 * <search> RediSearch version 2.6.12 (Git=HEAD-11b44a2d)
archivist-redis  | 8:M 19 Nov 2023 02:41:05.675 * <search> Low level api version 1 initialized successfully
archivist-redis  | 8:M 19 Nov 2023 02:41:05.675 * <search> concurrent writes: OFF, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  10000, search pool size: 20, index pool size: 8, 
archivist-redis  | 8:M 19 Nov 2023 02:41:05.675 * <search> Initialized thread pool!
archivist-redis  | 8:M 19 Nov 2023 02:41:05.675 * <search> Enabled diskless replication
archivist-redis  | 8:M 19 Nov 2023 02:41:05.675 * <search> Enabled role change notification
archivist-redis  | 8:M 19 Nov 2023 02:41:05.675 * Module 'search' loaded from /opt/redis-stack/lib/redisearch.so
archivist-redis  | 8:M 19 Nov 2023 02:41:05.677 * <graph> Enabled role change notification
archivist-redis  | 8:M 19 Nov 2023 02:41:05.677 * <graph> Starting up RedisGraph version 2.10.12.
archivist-redis  | 8:M 19 Nov 2023 02:41:05.677 * <graph> Thread pool created, using 4 threads.
archivist-redis  | 8:M 19 Nov 2023 02:41:05.677 * <graph> Maximum number of OpenMP threads set to 4
archivist-redis  | 8:M 19 Nov 2023 02:41:05.677 * Module 'graph' loaded from /opt/redis-stack/lib/redisgraph.so
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * <timeseries> RedisTimeSeries version 10811, git_sha=4baae3147c93d2bff747b137b7f17ea560f23fbd
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * <timeseries> Redis version found by RedisTimeSeries : 6.2.13 - oss
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * <timeseries> loaded default CHUNK_SIZE_BYTES policy: 4096
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * <timeseries> loaded server DUPLICATE_POLICY: block
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * <timeseries> Setting default series ENCODING to: compressed
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * <timeseries> Detected redis oss
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * <timeseries> Enabled diskless replication
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * Module 'timeseries' loaded from /opt/redis-stack/lib/redistimeseries.so
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * <ReJSON> version: 20407 git sha: a4412b3 branch: HEAD
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * <ReJSON> Exported RedisJSON_V1 API
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * <ReJSON> Exported RedisJSON_V2 API
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * <ReJSON> Exported RedisJSON_V3 API
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * <ReJSON> Enabled diskless replication
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * <ReJSON> Created new data type 'ReJSON-RL'
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * Module 'ReJSON' loaded from /opt/redis-stack/lib/rejson.so
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * <search> Acquired RedisJSON_V3 API
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * <graph> Acquired RedisJSON_V1 API
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * <bf> RedisBloom version 2.4.5 (Git=unknown)
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * Module 'bf' loaded from /opt/redis-stack/lib/redisbloom.so
archivist-redis  | 8:M 19 Nov 2023 02:41:05.678 * Ready to accept connections
tubearchivist    | ... Redis connection failed, retry [2/10]
tubearchivist    | ... Redis connection failed, retry [3/10]
tubearchivist    | ... Redis connection failed, retry [4/10]
tubearchivist    | ... Redis connection failed, retry [5/10]
tubearchivist    | ... Redis connection failed, retry [6/10]
tubearchivist    | ... Redis connection failed, retry [7/10]
tubearchivist    | ... Redis connection failed, retry [8/10]
tubearchivist    | ... Redis connection failed, retry [9/10]
tubearchivist    | Traceback (most recent call last):
tubearchivist    |   File "/app/manage.py", line 23, in <module>
tubearchivist    |     main()
tubearchivist    |   File "/app/manage.py", line 19, in main
tubearchivist    |     execute_from_command_line(sys.argv)
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
tubearchivist    |     utility.execute()
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 382, in execute
tubearchivist    |     settings.INSTALLED_APPS
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
tubearchivist    |     self._setup(name)
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
tubearchivist    |     self._wrapped = Settings(settings_module)
tubearchivist    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/root/.local/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
tubearchivist    |     mod = importlib.import_module(self.SETTINGS_MODULE)
tubearchivist    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
tubearchivist    |     return _bootstrap._gcd_import(name[level:], package, level)
tubearchivist    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
tubearchivist    |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
tubearchivist    |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
tubearchivist    |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
tubearchivist    |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
tubearchivist    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
tubearchivist    |   File "/app/config/settings.py", line 20, in <module>
tubearchivist    |     from home.src.ta.helper import ta_host_parser
tubearchivist    |   File "/app/home/__init__.py", line 3, in <module>
tubearchivist    |     from .tasks import app as celery_app
tubearchivist    |   File "/app/home/tasks.py", line 23, in <module>
tubearchivist    |     from home.src.index.manual import ImportFolderScanner
tubearchivist    |   File "/app/home/src/index/manual.py", line 24, in <module>
tubearchivist    |     class ImportFolderScanner:
tubearchivist    |   File "/app/home/src/index/manual.py", line 31, in ImportFolderScanner
tubearchivist    |     CONFIG = AppConfig().config
tubearchivist    |              ^^^^^^^^^^^
tubearchivist    |   File "/app/home/src/ta/config.py", line 22, in __init__
tubearchivist    |     self.config = self.get_config()
tubearchivist    |                   ^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/app/home/src/ta/config.py", line 26, in get_config
tubearchivist    |     config = self.get_config_redis()
tubearchivist    |              ^^^^^^^^^^^^^^^^^^^^^^^
tubearchivist    |   File "/app/home/src/ta/config.py", line 54, in get_config_redis
tubearchivist    |     raise ConnectionError("failed to connect to redis")
tubearchivist    | ConnectionError: failed to connect to redis
tubearchivist exited with code 0
```

### Anything else?

Copy of docker-compose.yml file below (all I've tried to customise so far are the storage volumes)

```
version: '3.5'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8000:8000
    volumes:
      - /pool2/youtube
      - cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200       # needs protocol e.g. http and port
      - REDIS_HOST=tubearchivist-redis      # don't add protocol
      - TA_HOST=tubearchivist.local.            # set your host name
      - TA_USERNAME=admin                        # your initial TA credentials
      - TA_PASSWORD=OMMITTED              # your initial TA credentials
      - ELASTIC_PASSWORD=OMMITTED    # set password for Elasticsearch
      - TZ=Europe/London                             # set your time zone
      - ENABLE_CAST=True
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-redis
      - archivist-es
  archivist-redis:
    image: "redis/redis-stack-server:6.2.6-v9"
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.11.0
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=OMMITTED"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"

volumes:
  cache:
  redis:
  es:

```
