### ISSUE TITLE
[Bug]: random crash every few days

### ISSUE THREAD

**Issue by hugalafutro** [tubearchivist/tubearchivist#619]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

docker in debian vm

## Describe the bug
random crash

## Steps To Reproduce
none, I just get notification from container-mon randomly that the container is not healthy completely at random with no rhyme or reason

## Expected behavior
no crash

### Relevant log output

```shell
log too long - uploaded to my privatebin https://o.o5.ddns.net/tiykE
```

### Anything else?

`docker compose up -d` brings the stack back as if nothing happened and then it works for days/weeks until randomly this issue.

my `docker-compose.yml`

```
version: "3.8"
services:
  tubearchivist:
    container_name: tubearchivist
    restart: always
    image: bbilly1/tubearchivist
    ports:
      - 8543:8000
    volumes:
      - /mnt/t-a:/youtube
      - ./data/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200
      - TA_HOST=${TA_HOSTLIST}
      - REDIS_HOST=archivist-redis
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_USERNAME=${TA_NAME}
      - TA_PASSWORD=${TA_PASS}
      - ELASTIC_PASSWORD=${ES_PASS}
      - TZ=${TIZO}
    depends_on:
      - archivist-es
      - archivist-redis

  archivist-redis:
    image: redis/redis-stack-server
#    image: redis/redis-stack-server:6.2.6-v9
    container_name: archivist-redis
    restart: always
    expose:
      - "6379"
    volumes:
      - ./data/redis:/data
    depends_on:
      - archivist-es

  archivist-es:
    image: bbilly1/tubearchivist-es
    container_name: archivist-es
    restart: always
    environment:
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=${ES_PASS}"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    deploy:
      resources:
        limits:
          memory: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    expose:
      - "9200"
```
