### ISSUE TITLE
[Feature Request]: KEYDB/VALKEY and OpenSearch validation

### ISSUE THREAD

**Issue by jtwolfe** [tubearchivist/tubearchivist#758]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
There is technically an issue related to this request.

## Describe the solution you'd like
I would like to be able to use keydb or valkey with tubearchivist.
AFAIK for the docker-compose deployment they should be drop in replacements with some minor variables to ensure that they function as expected. Unfortunately i keep getting some errors related to a file `/app/home/src/ta/config.py` that throws an error `failed to connect to redis`... im assuming that this is due to there being some 'redis exclusive' functionality that is addressed somehow by `ta_redis.py` or something further down the line.
Replacing ES with OpenSearch seems kinda trivial in comparison, as i try to drop in i get a version check error :| ie it expects es8 but gets os2.15.0, cause appears to be in here `tubearchivist/config/management/commands
/ta_connection.py` at ln111.

## Additional context
I would like to look more into this but I expect that this would be a pretty easy fix for someone who understands the codebase a bit better that my 10 minutes of staring blankly at __init__.py files :P i might build TA myself with a hack for OpenSearch to validate in a week or so, but im currently workin through my todo list of application testing.

PS maybe a jellyseerr plugin too in the future <3 ;)

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by jtwolfe** [comment]
ill check that little box if i get time in a bit

**Comment by jtwolfe** [comment]
see below the adjusted compose file for the OpenSearch I used to test for reference
```
version: '3.5'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8000:8000
    volumes:
      - media:/youtube
      - cache:/cache
    environment:
      - ES_URL=http://archivist-os:9200     # updated to OpenSearch URL
      - REDIS_HOST=archivist-redis          
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=tubearchivist.local         
      - TA_USERNAME=tubearchivist           
      - TA_PASSWORD=verysecret              
      - ELASTIC_PASSWORD=verysecret         
      - TZ=America/New_York                 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-os
      - archivist-redis
  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis:/data
    depends_on:
      - archivist-os
  archivist-os:
    image: opensearchproject/opensearch:latest
    container_name: archivist-os
    restart: unless-stopped
    environment:
      - "OPENSEARCH_PASSWORD=verysecret"       # matching OpenSearch password
      - "DISABLE_SECURITY_PLUGIN=true"         # disable security plugin if not needed
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - os_data:/usr/share/opensearch/data    
    expose:
      - "9200"

volumes:
  media:
  cache:
  redis:
  os_data:

```
