### ISSUE TITLE
[Installation]: Redis: Failed loading RedisAI API

### ISSUE THREAD

**Issue by drinksomewhiskey** [tubearchivist/tubearchivist#877]
### Installation instructions

- [x] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

Synology

### Your installation or setup question

Hi all,

As many of you, my previously working Synology install of TA stopped working due to the es container updates. I was following Dr F's guide to reinstall using docker compose: https://drfrankenstein.co.uk/tube-archivist-in-container-manager-on-a-synology-nas/

I keep getting an error in the redis container log stating: Failed loading RedisAI API

I have tried deleting everything and starting fresh, but have had no luck. Any suggestions?

### Relevant log output

```Shell
8:C 17 Feb 2025 04:14:26.140 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

02/16/202508:14:26 PM 8:C 17 Feb 2025 04:14:26.140 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo

02/16/202508:14:26 PM 8:C 17 Feb 2025 04:14:26.140 * Redis version=7.4.2, bits=64, commit=00000000, modified=0, pid=8, just started

02/16/202508:14:26 PM 8:C 17 Feb 2025 04:14:26.140 * Configuration loaded

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.141 * monotonic clock: POSIX clock_gettime

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.141 * Running mode=standalone, port=6379.

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.141 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.204 * Module 'RedisCompat' loaded from /opt/redis-stack/lib/rediscompat.so

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.482 * <search> Redis version found by RedisSearch : 7.4.2 - oss

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.482 * <search> RediSearch version 2.10.12 (Git=2.10.12-6d25a0b)

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.482 * <search> Low level api version 1 initialized successfully

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.482 * <search> gc: ON, prefix min length: 2, min word length to stem: 4, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results: 10000,

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.482 * <search> Initialized thread pools!

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.482 * <search> Enabled role change notification

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.482 * Module 'search' loaded from /opt/redis-stack/lib/redisearch.so

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.708 * <timeseries> RedisTimeSeries version 11205, git_sha=c0311e65891c3319e390370fe4d4532847c5b1e7

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.708 * <timeseries> Redis version found by RedisTimeSeries : 7.4.2 - oss

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.708 * <timeseries> loaded default CHUNK_SIZE_BYTES policy: 4096

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.708 * <timeseries> loaded server DUPLICATE_POLICY: block

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.708 * <timeseries> loaded default IGNORE_MAX_TIME_DIFF: 0

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.708 * <timeseries> loaded default IGNORE_MAX_VAL_DIFF: 0.000000

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.708 * <timeseries> Setting default series ENCODING to: compressed

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.708 * <timeseries> Detected redis oss

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.708 * Module 'timeseries' loaded from /opt/redis-stack/lib/redistimeseries.so

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.807 * <ReJSON> Created new data type 'ReJSON-RL'

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.808 # <ReJSON> Skip register defrag callbacks as defrag callbacks is not supported on the current Redis server.

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.808 * <ReJSON> version: 20808 git sha: unknown branch: unknown

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.808 * <ReJSON> Exported RedisJSON_V1 API

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.808 * <ReJSON> Exported RedisJSON_V2 API

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.808 * <ReJSON> Exported RedisJSON_V3 API

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.808 * <ReJSON> Exported RedisJSON_V4 API

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.808 * <ReJSON> Exported RedisJSON_V5 API

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.808 * <ReJSON> Enabled diskless replication

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.808 * <ReJSON> Initialized shared string cache, thread safe: false.

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.808 * Module 'ReJSON' loaded from /opt/redis-stack/lib/rejson.so

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.808 * <search> Acquired RedisJSON_V5 API

02/16/202508:14:26 PM 8:M 17 Feb 2025 04:14:26.851 * <bf> RedisBloom version 2.8.5 (Git=unknown)

02/16/202508:14:28 PM 8:M 17 Feb 2025 04:14:26.852 * Module 'bf' loaded from /opt/redis-stack/lib/redisbloom.so

02/16/202508:14:28 PM 8:M 17 Feb 2025 04:14:26.931 * <redisgears_2> Created new data type 'GearsType'

02/16/202508:14:28 PM 8:M 17 Feb 2025 04:14:26.932 * <redisgears_2> Detected redis oss

02/16/202508:14:28 PM 8:M 17 Feb 2025 04:14:26.933 # <redisgears_2> could not initialize RedisAI_InitError

02/16/202508:14:28 PM

02/16/202508:14:28 PM 8:M 17 Feb 2025 04:14:26.933 * <redisgears_2> Failed loading RedisAI API.

02/16/202508:14:28 PM 8:M 17 Feb 2025 04:14:26.933 * <redisgears_2> RedisGears v2.0.20, sha='9b737886bf825fe29ddc2f8da81f73cbe0b4e858', build_type='release', built_for='Linux-ubuntu22.04.x86_64', redis_version:'7.4.2', enterprise:'false'.

02/16/202508:14:28 PM 8:M 17 Feb 2025 04:14:27.305 * <redisgears_2> Registered backend: js.

02/16/202508:14:28 PM 8:M 17 Feb 2025 04:14:27.361 * Module 'redisgears_2' loaded from /opt/redis-stack/lib/redisgears.so

02/16/202508:14:28 PM 8:M 17 Feb 2025 04:14:27.361 * Server initialized

02/16/202508:14:28 PM 8:M 17 Feb 2025 04:14:27.361 * Ready to accept connections tcp
```

**Comment by lamusmaser** [comment]
This is informational only and not required for the functioning of Redis. The main line we want to see to ensure connection capability to Redis is this one: 
```
02/16/202508:14:28 PM 8:M 17 Feb 2025 04:14:27.361 * Ready to accept connections tcp
```

Without this, Redis isn't listening. If you are unable to connect to Redis, and this line is present, then usually the issue is elsewhere (networking, config, or something else).

**Comment by drinksomewhiskey** [comment]
Any idea where to check? Happy to post other logs if you have suggestions. The tube archivist container keeps trying to connect to redis but fails.

**Comment by lamusmaser** [comment]
The compose file will be the most helpful.

**Comment by drinksomewhiskey** [comment]
Thank you for helping me out!

Here it is:

```
services:
  tube_archivist:
    container_name: tube_archivist
    image: bbilly1/tubearchivist
    ports:
      - 8770:8000/tcp
    volumes:
      - /volume1/Libraries/Videos/YouTube/Tube Archivist:/youtube
      - /volume1/docker/tube_archivist/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200
      - REDIS_HOST=archivist-redis
      - HOST_UID=1030 #CHANGE_TO_YOUR_UID
      - HOST_GID=100 #CHANGE_TO_YOUR_GID
      - TA_HOST=192.168.1.57 #Change to your NAS IP
      - TA_USERNAME=admin #Username for login
      - TA_PASSWORD=@qDnH!KA2x9.MCH #password for login
      - ELASTIC_PASSWORD=etubearchivistpass # set password for Elasticsearch
      - TZ=America/Los_Angeles #CHANGE_TO_YOUR_TZ
    depends_on:
      - tube_archivist_es
      - tube_archivist_redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
  
  tube_archivist_redis:
    image: redis/redis-stack-server
    container_name: tube_archivist_redis
    expose:
      - "6379"
    environment:
      - HOST_UID=999
      - HOST_GID=100
    volumes:
      - /volume1/docker/tube_archivist/redis:/data
    depends_on:
      - tube_archivist_es
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5

  tube_archivist_es:
    image: bbilly1/tubearchivist-es:8.14.3
    container_name: tube_archivist_es
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/data/snapshot
      - ELASTIC_PASSWORD=tubearchivistpass #same password from above
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /volume1/docker/tube_archivist/es:/usr/share/elasticsearch/data
    expose:
      - "9200"
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5

```
