### ISSUE TITLE
[Frontend Migration]: unexpected env var REDIS_HOST found

### ISSUE THREAD

**Issue by icolumbro** [tubearchivist/tubearchivist#893]
### Domain

Combined

### Description

I tried to follow tutorial to migrate to version 0.5.0 from version 0.4.13, this is my docker-compose.yml:
```
services:
  tubearchivist:
    image: bbilly1/tubearchivist
    container_name: tubearchivist
    volumes:
      - /media/bazinga/downloads/TubeArchivist:/youtube
      - cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200
      - REDIS_HOST=archivist-redis
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=tubearchivist.mydomain.com
      - TA_USERNAME=username
      - TA_PASSWORD=password
      - ELASTIC_PASSWORD=password
      - TZ=Europe/Rome
    healthcheck:
      test: ["CMD", "curl", "-f", "https://tubearchivist.mydomain.com/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
      - archivist-redis
    networks:
      - nginx-proxy-manager_default
    labels:
      - docker-volume-backup.stop-during-backup=tubearchivist-volumes
    restart: unless-stopped

  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    expose:
      - "6379"
    volumes:
      - redis:/data
    depends_on:
      - archivist-es
    networks:
      - nginx-proxy-manager_default
    labels:
      - docker-volume-backup.stop-during-backup=tubearchivist-volumes
    restart: unless-stopped

  archivist-es:
    image: bbilly1/tubearchivist-es
    container_name: archivist-es
    environment:
      - "ELASTIC_PASSWORD=password"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    expose:
      - "9200"
    networks:
      - nginx-proxy-manager_default
    labels:
      - docker-volume-backup.stop-during-backup=tubearchivist-volumes
    restart: unless-stopped

  backup:
    image: offen/docker-volume-backup:latest
    env_file: stack.env
    volumes:
      - cache:/backup/tubearchivist_cache_bak:ro
      - redis:/backup/tubearchivist_redis_bak:ro
      - es:/backup/tubearchivist_es_bak:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /media/vault/docker/volumes/tubearchivist:/archive
    restart: always

volumes:
  cache:
  redis:
  es:

networks:
  nginx-proxy-manager_default:
    external: true
```
in the log I read:
```
#######################

#  Environment Setup  #

#######################

[1] checking expected env vars

    ✓ all expected env vars are set

[2] checking for unexpected env vars

    🗙 unexpected env var REDIS_HOST found

    Has been replaced with 'REDIS_CON' connection string 

    see release notes for a list of all changes.
```
