### ISSUE TITLE
[Bug]: New Instance doesn't allow log ins.

### ISSUE THREAD

**Issue by Handrail9** [tubearchivist/tubearchivist#940]
## If You're Experiencing This Issue,
Please leave a "thumbs up" react to the post *unless* you have new information that may be able to help lamusmaser. Comments that are variants of "+1" and "Me Too" tend to make it harder to debug and follow the issue (as well as blowing up email alerts). Thanks!

### I've read the documentation

- [x] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [x] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Fedora 41 Server

## Describe the bug
Following the instructions in the readme, as well as double checking myself in the docs, I am not able to create a properly working instance as no matter what I do the instance says "Failed to login. Invalid credentials"
## Steps To Reproduce
Create the compose.yaml file that can be found in the repo, add the env variables (I used the Username "youtube" and the password "youtube1" for testing purposes.) and start the container.
## Expected behavior
Be able to log in with user "youtube" and password "youtube1". I tested in both Firefox and Chrome to make sure this was not a browser issue.

### Relevant log output

```shell
Added as a txt file, Github is complaining it is more than 60k characters and will not allow me to post otherwise
```

### Anything else?

[logs.txt](https://github.com/user-attachments/files/19725036/logs.txt)
Docker Compose file:
```
services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8000:8000
    volumes:
      - media:/youtube
      - cache:/cache
    environment:
      - ES_URL=${ES_URL} # needs protocol e.g. http and port
      - REDIS_CON=${REDIS_CON}
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=${TA_HOST} # set your host name with protocol and port
      - TA_USERNAME="youtube" # your initial TA credentials
      - TA_PASSWORD="youtube1" # your initial TA credentials
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD} # set password for Elasticsearch
      - TZ=${TZ} # set your time zone
      - TA_ENABLE_AUTH_PROXY=${TA_ENABLE_AUTH_PROXY}
      - DJANGO_DEBUG=True
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8000/api/health
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redis
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es # only for amd64, or use official es 8.17.2
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD} # set password for Elasticsearch
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/data/snapshot
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data # check for permission error when using bind mount, see readme
    expose:
      - "9200"
volumes:
  media: null
  cache: null
  redis: null
  es: null
networks: {}
```
Env file:
```
TA_HOST=http://192.168.1.2:8000
TA_USERNAME="youtube"
TA_PASSWORD="youtube1"
ELASTIC_PASSWORD="removed"
ES_URL=http://archivist-es:9200
REDIS_CON=redis://archivist-redis:6379
TZ=America/New_York
TA_ENABLE_AUTH_PROXY=false # Was going to change this to true after I got it working.
```

I tried removing and recreating the sqlite database multiple times (Deleted the cache volume and recreated the container) but this did not provide different results. SELinux was set to permissive mode (off) while testing. If I can provide any more information please do not hesitate to ask. :)
